#!/usr/bin/env node
/* eslint-disable no-console -- Build-time CLI script; console output is the intended user feedback channel. */
/**
 * Prepend a /*! ... *\/ header banner to every JavaScript and CSS file under
 * the build/ directory. The header documents:
 *
 *   - the human-readable source entry that produced the file,
 *   - the source directories that contribute modules to the bundle,
 *   - the public source repository URL,
 *   - the build command used to regenerate the file.
 *
 * This script runs after `wp-scripts build` (see the "build" entry in
 * package.json). It is required by the WordPress.org Plugins Team review
 * guideline "Code must be mostly human-readable": every compiled file must
 * be traceable back to its public source.
 *
 * Re-running the script is idempotent: an existing banner with the same
 * "Airygen SEO" marker is replaced rather than stacked.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname( fileURLToPath( import.meta.url ) );
const repoRoot = path.resolve( __dirname, '..' );
const buildDir = path.join( repoRoot, 'build' );

const REPO_URL = 'https://github.com/airygen/airygen-seo';
const REPO_BRANCH = 'main';
const BUILD_COMMAND = 'pnpm build';

/**
 * Build a GitHub URL pointing at the same path inside the public source tree.
 *
 * Directories (paths ending with `/`) use `/tree/{branch}/...`; files use
 * `/blob/{branch}/...`. Reviewers can click each path to inspect the
 * unminified source that produced the compiled file.
 *
 * @param {string} sourcePath Relative path inside the repository (e.g.
 *                            `packages/admin/components/` or
 *                            `packages/block-editor/config.ts`).
 * @return {string} Full GitHub URL.
 */
function githubUrlFor( sourcePath ) {
	const isDir = sourcePath.endsWith( '/' );
	const kind = isDir ? 'tree' : 'blob';
	return `${ REPO_URL }/${ kind }/${ REPO_BRANCH }/${ sourcePath }`;
}

/**
 * Map from compiled file (relative to build/) to its source description.
 * `entry` is the webpack entry; `styleEntry` (optional) describes the CSS
 * pipeline for the bundle. Stylesheets receive the styleEntry banner when
 * provided, JavaScript files always receive the entry banner.
 */
const bundles = {
	'admin/airygen-app.js': {
		entry: 'packages/admin/app.tsx',
		sourceDirs: [
			'packages/admin/components/',
			'packages/admin/pages/',
			'packages/admin/utils/',
			'packages/admin/types/',
			'packages/admin/constants/',
			'packages/admin/styles/',
			'packages/shared/',
		],
	},
	'admin/app.tsx.css': {
		entry: 'packages/admin/styles/tailwind.css',
		styleEntry: 'packages/admin/styles/tailwind.css (Tailwind CSS scanning packages/admin/**/*.{tsx,ts}; see tailwind.config.js + postcss.config.js)',
		sourceDirs: [ 'packages/admin/', 'packages/shared/' ],
	},
	'admin/app.tsx-rtl.css': {
		entry: 'packages/admin/styles/tailwind.css',
		styleEntry: 'packages/admin/styles/tailwind.css (Tailwind CSS, RTL variant generated by @wordpress/scripts)',
		sourceDirs: [ 'packages/admin/', 'packages/shared/' ],
	},
	'block-editor/airygen-editor.js': {
		entry: 'packages/block-editor/src/index.tsx',
		sourceDirs: [
			'packages/block-editor/components/',
			'packages/block-editor/hooks/',
			'packages/block-editor/utils/',
			'packages/block-editor/config.ts',
			'packages/block-editor/types.ts',
			'packages/shared/',
		],
	},
	'block-editor/style-block-editor.css': {
		entry: 'packages/block-editor/style.scss',
		styleEntry: 'packages/block-editor/style.scss (Sass + PostCSS)',
		sourceDirs: [ 'packages/block-editor/' ],
	},
	'block-editor/style-block-editor-rtl.css': {
		entry: 'packages/block-editor/style.scss',
		styleEntry: 'packages/block-editor/style.scss (Sass + PostCSS, RTL variant)',
		sourceDirs: [ 'packages/block-editor/' ],
	},
	'classic-editor/airygen-editor.js': {
		entry: 'packages/classic-editor/src/index.tsx',
		sourceDirs: [
			'packages/classic-editor/components/',
			'packages/shared/',
		],
	},
	'classic-editor/style-classic-editor.css': {
		entry: 'packages/classic-editor/style.scss',
		styleEntry: 'packages/classic-editor/style.scss (Sass + PostCSS)',
		sourceDirs: [ 'packages/classic-editor/' ],
	},
	'classic-editor/style-classic-editor-rtl.css': {
		entry: 'packages/classic-editor/style.scss',
		styleEntry: 'packages/classic-editor/style.scss (Sass + PostCSS, RTL variant)',
		sourceDirs: [ 'packages/classic-editor/' ],
	},
};

const BANNER_START_MARKER = '/*! Airygen SEO';
const BANNER_END_MARKER = '*/';

function buildBanner( relativePath, info ) {
	const isCss = relativePath.toLowerCase().endsWith( '.css' );
	const entryLine = isCss && info.styleEntry ? info.styleEntry : info.entry;

	// One source directory per line, paired with its public GitHub URL on the
	// following line. Reviewers can scan local paths quickly and click through
	// to the unminified source without manually constructing URLs.
	const sourceLines = info.sourceDirs.flatMap( ( dir ) => [
		` *   - ${ dir }`,
		` *     ${ githubUrlFor( dir ) }`,
	] );

	return [
		`${ BANNER_START_MARKER } compiled asset`,
		` * File:               build/${ relativePath }`,
		` * Source entry:       ${ entryLine }`,
		' * Source directories:',
		...sourceLines,
		` * Repository:         ${ REPO_URL }`,
		` * Build command:      ${ BUILD_COMMAND }`,
		' *',
		' * The unminified TypeScript / JSX / SCSS sources that produced this file',
		' * live at the GitHub paths listed above. See readme.txt "Source code"',
		' * for the full source-to-build mapping and local build instructions.',
		` ${ BANNER_END_MARKER }`,
		'',
	].join( '\n' );
}

function stripExistingBanner( contents ) {
	if ( ! contents.startsWith( BANNER_START_MARKER ) ) {
		return contents;
	}
	const end = contents.indexOf( BANNER_END_MARKER );
	if ( end === -1 ) {
		return contents;
	}
	let cursor = end + BANNER_END_MARKER.length;
	while ( cursor < contents.length && ( contents[ cursor ] === '\n' || contents[ cursor ] === '\r' ) ) {
		cursor += 1;
	}
	return contents.slice( cursor );
}

async function annotate( relativePath, info ) {
	const absolute = path.join( buildDir, relativePath );
	if ( ! existsSync( absolute ) ) {
		console.warn( `[build-banner] Skipping ${ relativePath } (file not found)` );
		return;
	}

	const original = await readFile( absolute, 'utf8' );
	const stripped = stripExistingBanner( original );
	const banner = buildBanner( relativePath, info );
	await writeFile( absolute, banner + stripped, 'utf8' );
	console.log( `[build-banner] Annotated build/${ relativePath }` );
}

async function main() {
	if ( ! existsSync( buildDir ) ) {
		console.error( `[build-banner] build/ directory not found at ${ buildDir }` );
		process.exit( 1 );
	}

	for ( const [ relativePath, info ] of Object.entries( bundles ) ) {
		await annotate( relativePath, info );
	}
}

main().catch( ( err ) => {
	console.error( '[build-banner] Failed to annotate build assets:', err );
	process.exit( 1 );
} );
